# Generated by Django 5.2.8 on 2025-11-17 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_remove_product_stock_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id_bom', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StasiunKerja',
            fields=[
                ('id_stasiun_kerja', models.AutoField(primary_key=True, serialize=False)),
                ('nama_stasiun_kerja', models.CharField(max_length=200)),
                ('keterangan', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BOMDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('satuan', models.CharField(max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacture.bom')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('id_rawmaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.rawmaterial')),
                ('id_stasiunkerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacture.stasiunkerja')),
            ],
            options={
                'unique_together': {('id_bom', 'id_product', 'id_rawmaterial')},
            },
        ),
    ]
