# Generated by Django 5.2.8 on 2025-11-17 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0001_initial'),
        ('product', '0002_remove_product_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='id_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='bom',
            name='nama_product',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
