# Generated by Django 5.2.8 on 2025-11-18 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0002_bom_id_product_bom_nama_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bom',
            name='nama_product',
        ),
    ]
