# Generated by Django 5.2.8 on 2025-11-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0003_remove_bom_nama_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomdetail',
            name='nama_product',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bomdetail',
            name='nama_rawmaterial',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
