# Generated by Django 5.2.8 on 2025-11-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0004_bomdetail_nama_product_bomdetail_nama_rawmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomdetail',
            name='nama_stasiunkerja',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
