# Generated by Django 5.2.8 on 2025-11-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0005_bomdetail_nama_stasiunkerja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='id_bom',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
