# Generated by Django 5.2.8 on 2025-11-18 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0006_alter_bom_id_bom'),
        ('product', '0002_remove_product_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bomdetail',
            unique_together={('id_bom', 'id_product', 'id_rawmaterial', 'version')},
        ),
    ]
