# Generated by Django 5.2.8 on 2025-11-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0007_alter_bomdetail_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomdetail',
            name='harga_satuanrawmaterial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bomdetail',
            name='harga_totalrawmaterial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
