# Generated by Django 5.2.8 on 2025-11-18 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0008_bomdetail_harga_satuanrawmaterial_and_more'),
        ('product', '0002_remove_product_stock_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id_po', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tanggal_request', models.DateField()),
                ('tanggal_selesai', models.DateField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bomdetail',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='ProductionOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_product', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=50)),
                ('warna', models.CharField(max_length=50)),
                ('qty_produksi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('keterangan', models.TextField(blank=True)),
                ('id_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacture.productionorder')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'unique_together': {('id_po', 'id_product')},
            },
        ),
    ]
