# Generated by Django 5.2.8 on 2025-11-18 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0009_productionorder_alter_bomdetail_unique_together_and_more'),
        ('product', '0002_remove_product_stock_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratPerintahKerja',
            fields=[
                ('id_spk', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tanggal_spk', models.DateField()),
                ('status', models.CharField(default='Draft', max_length=50)),
                ('keterangan', models.TextField(blank=True)),
                ('id_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacture.productionorder')),
            ],
        ),
        migrations.CreateModel(
            name='SPKOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_stasiunkerja', models.CharField(blank=True, max_length=200)),
                ('nama_product', models.CharField(max_length=200)),
                ('qty_output', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('id_stasiunkerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacture.stasiunkerja')),
                ('id_spk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacture.suratperintahkerja')),
            ],
        ),
        migrations.CreateModel(
            name='SPKDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_stasiunkerja', models.CharField(blank=True, max_length=200)),
                ('nama_rawmaterial', models.CharField(blank=True, max_length=200)),
                ('qty_kebutuhan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('satuan', models.CharField(max_length=50)),
                ('id_rawmaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.rawmaterial')),
                ('id_stasiunkerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacture.stasiunkerja')),
                ('id_spk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacture.suratperintahkerja')),
            ],
        ),
    ]
