# Generated by Django 5.2.8 on 2025-11-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0010_suratperintahkerja_spkoutput_spkdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suratperintahkerja',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved')], default='Draft', max_length=50),
        ),
    ]
