# Generated by Django 5.2.8 on 2025-11-19 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0011_alter_suratperintahkerja_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorderdetail',
            name='qty_remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='spkoutput',
            name='id_po_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacture.productionorderdetail'),
        ),
    ]
