# Generated by Django 5.2.8 on 2025-11-19 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0012_productionorderdetail_qty_remaining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spkoutput',
            name='id_stasiunkerja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacture.stasiunkerja'),
        ),
    ]
