# Generated by Django 5.2.8 on 2025-11-19 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0013_alter_spkoutput_id_stasiunkerja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spkoutput',
            name='id_stasiunkerja',
        ),
        migrations.RemoveField(
            model_name='spkoutput',
            name='nama_stasiunkerja',
        ),
    ]
