# Generated by Django 5.2.8 on 2025-11-19 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0014_remove_spkoutput_id_stasiunkerja_and_more'),
        ('product', '0002_remove_product_stock_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_product', models.CharField(blank=True, max_length=200)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('qty_selesai', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('id_spk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacture.suratperintahkerja')),
                ('id_stasiunkerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacture.stasiunkerja')),
            ],
        ),
    ]
