# Generated by Django 5.2.8 on 2025-11-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='supplier',
        ),
    ]
