# Generated by Django 5.2.8 on 2025-11-17 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_product', '0001_initial'),
        ('product', '0002_remove_product_stock_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeluarRawMaterial',
            fields=[
                ('id_keluar', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tanggal_keluar', models.DateField()),
                ('keterangan', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PenerimaanRawMaterial',
            fields=[
                ('id_penerimaan', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('id_supplier', models.CharField(max_length=100)),
                ('tanggal_terima', models.DateField()),
                ('keterangan', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawmaterial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='KeluarRawMaterialDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_keluar', models.DateField()),
                ('BRAND', models.CharField(max_length=100)),
                ('Nama_rawmaterial', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harga_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kategori', models.CharField(max_length=100)),
                ('id_keluar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_product.keluarrawmaterial')),
                ('id_rawmaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='PenerimaanRawMaterialDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_terima', models.DateField()),
                ('Supplier', models.CharField(max_length=200)),
                ('BRAND', models.CharField(max_length=100)),
                ('Nama_rawmaterial', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('satuan', models.CharField(max_length=50)),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harga_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kategori', models.CharField(max_length=100)),
                ('id_penerimaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_product.penerimaanrawmaterial')),
                ('id_rawmaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.rawmaterial')),
            ],
        ),
    ]
