# Generated by Django 5.2.8 on 2025-11-19 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_product', '0002_keluarrawmaterial_penerimaanrawmaterial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keluarrawmaterialdetail',
            name='harga_satuan',
        ),
        migrations.RemoveField(
            model_name='keluarrawmaterialdetail',
            name='harga_total',
        ),
    ]
