# Generated by Django 5.2.8 on 2025-11-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_product', '0003_remove_keluarrawmaterialdetail_harga_satuan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keluarrawmaterialdetail',
            name='harga_satuan',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='keluarrawmaterialdetail',
            name='harga_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
